const Map<String, String> stringsVi = {
  'app.name': 'DevConnect',
  'common.preview': 'Xem trước',
  'common.connected': 'Đã kết nối',
  'common.notLinked': 'Chưa liên kết',
  'common.public': 'Công khai',
  'common.private': 'Riêng tư',
  'common.everyone': 'Mọi người',
  'common.followers': 'Người theo dõi',
  'common.nobody': 'Không ai',
  'common.off': 'Tắt',
  'common.light': 'Sáng',
  'common.dark': 'Tối',
  'common.english': 'English',
  'common.vietnamese': 'Tiếng Việt',
  'common.version': 'Phiên bản',
  'common.logout': 'Đăng xuất',
  'common.save': 'Lưu',
  'common.cancel': 'Hủy',
  'common.delete': 'Xóa',
  'common.edit': 'Chỉnh sửa',
  'common.error': 'Đã xảy ra lỗi',
  'common.retry': 'Thử lại',
  'common.all': 'Tất cả',
  'common.mentions': 'Nhắc đến',
  'common.follows': 'Đang theo dõi',
  'common.today': 'Hôm nay',
  'common.earlier': 'Trước đó',
  'common.markAllRead': 'Đánh dấu đã đọc hết',
  'common.accept': 'Chấp nhận',
  'common.decline': 'Từ chối',
  'common.post': 'Bài viết',
  'common.findFeature': 'Tìm tính năng',
  'common.search': 'Tìm kiếm',
  'common.privateProfile': 'Hồ sơ riêng tư',
  'common.publicProfile': 'Hồ sơ công khai',
  'common.follow': 'Theo dõi',
  'common.following': 'Đang theo dõi',
  'common.message': 'Nhắn tin',
  'common.syncGithub': 'Đồng bộ GitHub',
  'common.synced': 'Đã đồng bộ',
  'common.noRecentContributions': 'Chưa có đóng góp gần đây',
  'common.featuredProject': 'Dự án nổi bật',
  'common.skills': 'Kỹ năng',
  'common.repos': 'Kho mã',
  'common.reputation': 'Uy tín',
  'common.memberSince': 'Thành viên từ',
  'common.mentor': 'Cố vấn',
  'common.availableForGuidance': 'Sẵn sàng hỗ trợ',
  'feed.forYou': 'Dành cho bạn',
  'feed.following': 'Đang theo dõi',
  'feed.trending': 'Xu hướng',
  'group.primary': 'Chính',
  'group.social': 'Xã hội',
  'group.opportunities': 'Cơ hội',
  'group.tools': 'Công cụ',
  'group.system': 'Hệ thống',
  'nav.home': 'Trang chủ',
  'nav.explore': 'Khám phá',
  'nav.chat': 'Chat',
  'nav.more': 'Thêm',
  'nav.notifications': 'Thông báo',
  'nav.profile': 'Hồ sơ',
  'nav.projects': 'Dự án',
  'nav.jobs': 'Việc làm',
  'nav.playground': 'Playground',
  'nav.analytics': 'Thống kê',
  'nav.leaderboard': 'Bảng xếp hạng',
  'nav.live-code': 'Xem code trực tiếp',
  'nav.settings': 'Cài đặt',
  'settings.title': 'Cài đặt',
  'settings.subtitle': 'Quản lý tài khoản, quyền riêng tư và tùy chọn của bạn',
  'settings.account': 'TÀI KHOẢN',
  'settings.privacy': 'RIÊNG TƯ',
  'settings.notifications': 'THÔNG BÁO',
  'settings.appearance': 'GIAO DIỆN',
  'settings.about': 'GIỚI THIỆU',
  'settings.editProfile': 'Sửa hồ sơ',
  'settings.changePassword': 'Đổi mật khẩu',
  'settings.githubIntegration': 'Tích hợp GitHub',
  'settings.deleteAccount': 'Xóa tài khoản',
  'settings.profileVisibility': 'Hiển thị hồ sơ',
  'settings.onlineStatus': 'Trạng thái trực tuyến',
  'settings.whoCanMessage': 'Ai có thể nhắn tin',
  'settings.pushNotifications': 'Thông báo đẩy',
  'settings.emailNotifications': 'Thông báo email',
  'settings.quietHours': 'Giờ yên lặng',
  'settings.theme': 'Chủ đề',
  'settings.language': 'Ngôn ngữ',
  'settings.version': 'Phiên bản',
  'settings.logout': 'Đăng xuất',
  'settings.public': 'Công khai',
  'settings.private': 'Riêng tư',
  'settings.languageEnglish': 'English',
  'settings.languageVietnamese': 'Tiếng Việt',
  'settings.displayNameRequired': 'Tên hiển thị là bắt buộc',
  'settings.editProfileSubtitle':
      'Cập nhật những thông tin cơ bản mọi người nhìn thấy trên hồ sơ của bạn.',
  'settings.profileUpdated': 'Đã cập nhật hồ sơ',
  'settings.newPasswordTooShort': 'Mật khẩu mới phải có ít nhất 8 ký tự',
  'settings.passwordsDoNotMatch': 'Mật khẩu không khớp',
  'settings.passwordChanged': 'Đã đổi mật khẩu',
  'settings.deleteAccountTitle': 'Xóa tài khoản?',
  'settings.deleteAccountBody':
      'Việc này sẽ xóa tài khoản khỏi thiết bị hiện tại và dữ liệu demo backend.',
  'settings.delete': 'Xóa',
  'settings.profileVisibilityTitle': 'Hiển thị hồ sơ',
  'settings.whoCanMessageTitle': 'Ai có thể nhắn tin',
  'settings.quietHoursTitle': 'Giờ yên lặng',
  'settings.newPassword': 'Mật khẩu mới',
  'settings.currentPassword': 'Mật khẩu hiện tại',
  'settings.confirmNewPassword': 'Xác nhận mật khẩu mới',
  'settings.updatePassword': 'Cập nhật mật khẩu',
  'settings.saveProfile': 'Lưu hồ sơ',
  'settings.displayName': 'Tên hiển thị',
  'settings.shortBio': 'Bio ngắn',
  'settings.skillsComma': 'Kỹ năng (ngăn cách bằng dấu phẩy)',
  'settings.publicProfile': 'Hồ sơ công khai',
  'settings.privateProfile': 'Hồ sơ riêng tư',
  'settings.connected': 'Đã kết nối',
  'settings.notLinked': 'Chưa liên kết',
  'settings.githubWebOnly': 'GitHub OAuth chỉ khả dụng qua redirect trên web.',
  'settings.savedLocallySyncLater': 'Đã lưu cục bộ. Sẽ đồng bộ lại sau.',
  'notifications.title': 'Thông báo',
  'notifications.subtitle': 'Theo dõi hoạt động và các lượt nhắc đến của bạn',
  'notifications.unableLoad': 'Không thể tải thông báo lúc này.',
  'notifications.today': 'Hôm nay',
  'notifications.earlier': 'Trước đó',
  'notifications.markAllRead': 'Đánh dấu đã đọc hết',
  'notifications.all': 'Tất cả',
  'notifications.mentions': 'Nhắc đến',
  'notifications.follows': 'Đang theo dõi',
  'notifications.empty': 'Chưa có thông báo nào.',
  'notifications.teamInvite': 'Bạn được mời tham gia tổ chức Team Flutter.',
  'notifications.accepted': 'Bạn đã tham gia Team Flutter.',
  'notifications.declined': 'Bạn đã từ chối lời mời Team Flutter.',
  'profile.userNotFound': 'Không tìm thấy người dùng',
  'profile.posts': 'Bài viết',
  'profile.projects': 'Dự án',
  'profile.about': 'Giới thiệu',
  'profile.followers': 'Người theo dõi',
  'profile.following': 'Đang theo dõi',
  'profile.online': 'Đang trực tuyến',
  'profile.offline': 'Ngoại tuyến',
  'profile.privateLockedTitle': 'Hồ sơ này đang riêng tư',
  'profile.privateLockedBody':
      'Chỉ người được cho phép mới xem được bài viết, dự án và chi tiết.',
  'profile.noProjectsTitle': 'Chưa có dự án',
  'profile.noProjectsBody':
      'Dự án sẽ xuất hiện ở đây sau khi người dùng tạo hoặc tham gia dự án.',
  'profile.gitHubConnected': 'GitHub đã kết nối',
  'profile.gitHubNotLinked': 'GitHub chưa liên kết',
  'profile.gitHubConnectHint':
      'Hãy kết nối GitHub bằng OAuth thật trước khi đồng bộ dữ liệu.',
  'profile.gitHubSynced': 'Đã đồng bộ dữ liệu GitHub',
  'profile.unableSyncGithub': 'Hiện không thể đồng bộ GitHub',
  'profile.noRecentContributions': 'Chưa có đóng góp gần đây',
  'profile.featuredProject': 'Dự án nổi bật',
  'profile.skills': 'Kỹ năng',
  'profile.repos': 'Kho mã',
  'profile.reputation': 'Uy tín',
  'profile.memberSince': 'Thành viên từ',
  'profile.mentor': 'Cố vấn',
  'profile.quitProject': 'Rời dự án',
  'profile.quitProjectConfirm': 'Bạn có chắc chắn muốn rời khỏi dự án này?',
  'profile.deleteProjectConfirm':
      'Bạn có chắc chắn muốn xóa dự án này? Không thể hoàn tác.',
  'profile.editSkills': 'Chỉnh sửa kỹ năng',
  'profile.addSkillsHint': 'Nhấn chỉnh sửa để thêm kỹ năng',
  'profile.noSkills': 'Chưa có kỹ năng',
  'feed.deletePostConfirm': 'Bạn có chắc chắn muốn xóa bài viết này?',
  'feed.postDeleted': 'Đã xóa bài viết',
  'profile.availableForGuidance': 'Sẵn sàng hỗ trợ',
  'more.title': 'Thêm',
  'more.findFeature': 'Tìm tính năng',
  'more.preview': 'Xem trước',
  'feed.empty': 'Chưa có bài viết nào.',
  'auth.resetPassword': 'Đặt lại mật khẩu',
  'auth.resetDescription':
      'Nhập email bạn dùng cho DevConnect. Chúng tôi sẽ bắt đầu quy trình khôi phục cho tài khoản đó.',
  'auth.emailAddress': 'Địa chỉ email',
  'auth.sendRecovery': 'Gửi hướng dẫn khôi phục',
  'auth.enterValidEmail': 'Nhập địa chỉ email hợp lệ',
  'auth.recoverySent':
      'Nếu tài khoản tồn tại, hướng dẫn khôi phục đang được gửi đi.',
  'auth.join': 'Gia nhập DevConnect',
  'auth.startJourney': 'Bắt đầu hành trình lập trình',
  'auth.fullName': 'Họ và tên',
  'auth.username': 'Tên người dùng',
  'auth.email': 'Địa chỉ email',
  'auth.password': 'Mật khẩu',
  'auth.continue': 'Tiếp tục',
  'auth.alreadyHaveAccount': 'Đã có tài khoản? ',
  'auth.signIn': 'Đăng nhập',
  'auth.secureAccount': 'Bảo vệ tài khoản của bạn',
  'auth.choosePassword': 'Chọn mật khẩu để bảo vệ hồ sơ',
  'auth.weakPassword': 'Mật khẩu yếu',
  'auth.averagePassword': 'Mật khẩu trung bình',
  'auth.goodPassword': 'Mật khẩu tốt',
  'auth.strongPassword': 'Mật khẩu mạnh',
  'auth.createAccount': 'Tạo tài khoản',
  'auth.accountCreated': 'Đã tạo tài khoản',
  'auth.finishSetup': 'Hoàn tất thiết lập',
  'auth.passwordMinLength': 'Mật khẩu phải có ít nhất 8 ký tự',
  'auth.completeAllFields': 'Vui lòng điền đầy đủ các trường',
  'auth.reset': 'Đặt lại',
  'errors.connectionTimeout': 'Kết nối quá hạn. Vui lòng kiểm tra mạng.',
  'errors.sendTimeout': 'Gửi yêu cầu quá hạn. Vui lòng thử lại.',
  'errors.receiveTimeout': 'Nhận phản hồi quá hạn. Vui lòng thử lại.',
  'errors.connectionError': 'Không thể kết nối. Vui lòng kiểm tra mạng.',
  'errors.badCertificate': 'Chứng chỉ bảo mật không hợp lệ.',
  'errors.cancelled': 'Yêu cầu đã bị hủy.',
  'errors.unknown': 'Đã xảy ra lỗi không xác định.',
  'errors.invalidRequest': 'Yêu cầu không hợp lệ.',
  'errors.sessionExpired': 'Phiên đăng nhập hết hạn. Vui lòng đăng nhập lại.',
  'errors.permissionDenied': 'Bạn không có quyền thực hiện thao tác này.',
  'errors.notFound': 'Không tìm thấy dữ liệu.',
  'errors.conflict': 'Xung đột dữ liệu. Vui lòng thử lại.',
  'errors.invalidData': 'Dữ liệu không hợp lệ.',
  'errors.tooManyRequests': 'Quá nhiều yêu cầu. Vui lòng chờ và thử lại.',
  'errors.serverError': 'Lỗi máy chủ. Vui lòng thử lại sau.',
  'errors.serviceUnavailable': 'Dịch vụ tạm thời không khả dụng.',
  'errors.generic': 'Đã xảy ra lỗi. Vui lòng thử lại.',
  'errors.expectedObjectButGotList': 'Dự kiến object nhưng nhận list.',

  // Validators
  'validators.required': 'Trường này là bắt buộc.',
  'validators.emailFormat': 'Email phải có dạng tên@miền.com',
  'validators.emailTooLong': 'Email không quá 254 ký tự',
  'validators.passwordTooShort': 'Mật khẩu cần ≥8 ký tự',
  'validators.passwordNeedsLetter': 'Mật khẩu cần ít nhất 1 chữ cái',
  'validators.passwordNeedsNumber': 'Mật khẩu cần ít nhất 1 chữ số',
  'validators.passwordNeedsSpecial': 'Mật khẩu cần ít nhất 1 ký tự đặc biệt',
  'validators.passwordsDoNotMatch': 'Mật khẩu xác nhận không khớp',
  'validators.usernameFormat': 'Tên dùng a-z, 0-9, _ và 3-30 ký tự',
  'validators.usernameStartsWithUnderscore': 'Tên không được bắt đầu bằng _',
  'validators.urlInvalid': 'URL không hợp lệ',
  'validators.urlMissingScheme': 'URL phải bắt đầu http:// hoặc https://',
  'ai.unableReview': 'Không thể review code',
  'ai.unableExplain': 'Không thể giải thích code',
  'ai.tryUpdateSnippet': 'Hãy cập nhật đoạn code rồi thử lại.',
  'ai.noMajorIssues': 'Không phát hiện lỗi lớn',
  'ai.snippetLooksClean':
      'Đoạn code đủ sạch để đăng hoặc demo ở trạng thái hiện tại.',
  'ai.line': 'Dòng',
  'ai.concepts': 'Khái niệm',
  'ai.alternatives': 'Phương án thay thế',
  'ai.complexity': 'Độ phức tạp',
  'ai.reviewInterrupted': 'Review bị gián đoạn',
  'ai.connectionLostReview': 'Mất kết nối. Hãy yêu cầu review lại.',
  'ai.reviewing': 'AI đang review...',
  'ai.reviewComplete': 'Review hoàn tất',
  'ai.explanationInterrupted': 'Giải thích bị gián đoạn',
  'ai.connectionLostExplanation': 'Mất kết nối. Hãy yêu cầu giải thích lại.',
  'ai.explaining': 'AI đang giải thích...',
  'ai.explanationComplete': 'Giải thích hoàn tất',
  'ai.thinking': 'AI đang suy nghĩ...',
  'ai.waitingResponse': 'Đang chờ phản hồi...',
  'ai.typing': 'Đang nhập...',
  // Projects
  'projects.title': 'Dự án',
  'projects.marketplace': 'Chợ dự án',
  'projects.marketplaceSubtitle':
      'Khám phá dự án mã nguồn mở và tìm cộng tác viên',
  'projects.all': 'Tất cả',
  'projects.lookingForDevs': 'Tìm lập trình viên',
  'projects.openSource': 'Mã nguồn mở',
  'projects.titleDescRequired': 'Tiêu đề và mô tả là bắt buộc',
  'projects.created': 'Dự án đã được tạo',
  'projects.join': 'Tham gia',
  'projects.joined': 'Đã tham gia',
  'projects.alreadyJoined': 'Bạn đã tham gia hoặc yêu cầu tham gia dự án này',
  'projects.unableJoin': 'Không thể tham gia dự án lúc này',
  'projects.members': 'thành viên',
  'projects.createProject': 'Tạo dự án',
  'projects.createSubtitle': 'Tạo không gian cộng tác mới cho cộng đồng.',
  'projects.projectTitle': 'Tên dự án',
  'projects.projectDescription': 'Mô tả dự án đang xây dựng',
  'projects.techStack': 'Công nghệ (ngăn cách bằng dấu phẩy)',
  'projects.maxMembers': 'Số thành viên tối đa',
  'projects.create': 'Tạo dự án',
  'projects.unableLoad': 'Không thể tải dự án.\nKéo xuống để thử lại.',
  'projects.noProjects': 'Chưa có dự án nào',
  'projects.noProjectsSubtitle': 'Quay lại sau hoặc tạo dự án mới.',
  // Jobs
  'jobs.title': 'Việc làm',
  'jobs.hiringPulse': 'Tình hình tuyển dụng',
  'jobs.openRoles': 'Vị trí mở',
  'jobs.remote': 'Từ xa',
  'jobs.avgMatch': 'Phù hợp TB',
  'jobs.topMatch': 'Phù hợp nhất',
  'jobs.recent': 'Mới nhất',
  'jobs.senior': 'Cấp cao',
  'jobs.applyNow': 'Ứng tuyển ngay',
  'jobs.applied': 'Đã ứng tuyển',
  'jobs.signInToApply': 'Đăng nhập để ứng tuyển',
  'jobs.applicationFailed': 'Ứng tuyển thất bại. Thử lại.',
  'jobs.unableLoad': 'Không thể tải việc làm.\nKéo xuống để thử lại.',
  'jobs.noJobs': 'Chưa có việc làm nào',
  'jobs.noJobsSubtitle': 'Quay lại sau để xem tin mới.',
  'jobs.match': 'phù hợp',
  'jobs.allLevels': 'Tất cả cấp độ',
  'jobs.junior': 'Junior',
  'jobs.mid': 'Mid',
  'jobs.allSalaries': 'Tất cả mức lương',
  'jobs.filterTech': 'Công nghệ',
  'jobs.postJob': 'Đăng việc',
  'jobs.postJobSubtitle': 'Tạo tin tuyển dụng mới cho công ty',
  'jobs.jobTitle': 'Tên vị trí',
  'jobs.company': 'Tên công ty',
  'jobs.location': 'Địa điểm (VD: TP.HCM)',
  'jobs.salary': 'Mức lương (VD: 15-25 triệu)',
  'jobs.experience': 'Kinh nghiệm (VD: Junior, Mid, Senior)',
  'jobs.techStackHint': 'Công nghệ yêu cầu (ngăn cách bằng dấu phẩy)',
  'jobs.posted': 'Đã đăng việc!',
  'jobs.titleCompanyRequired': 'Tên vị trí và công ty là bắt buộc',
  'jobs.matchExplain':
      '% phù hợp được tính bằng cách so sánh kỹ năng của bạn với tech stack của việc làm. Càng nhiều kỹ năng trùng = % càng cao.',
  'jobs.search': 'Tìm việc làm...',
  // Explore
  'explore.title': 'Khám phá',
  'explore.popularTopics': 'Chủ đề phổ biến',
  'explore.trendingPosts': 'Bài viết xu hướng',
  'explore.topDevelopers': 'Lập trình viên hàng đầu',
  'explore.seeAll': 'Xem tất cả',
  'explore.searchPlaceholder': 'Tìm bài viết, lập trình viên, dự án...',
  'explore.aiPicks': 'AI chọn cho bạn',
  // Feed
  'feed.defaultTitle': 'Bạn đang làm gì?',
  'feed.addContent': 'Thêm nội dung trước khi đăng',
  'feed.aiReview': 'AI kiểm duyệt trước khi đăng',
  'feed.keepEditing': 'Tiếp tục chỉnh sửa',
  'feed.postNow': 'Đăng ngay',
  'feed.post': 'Đăng',
  'feed.useGif': 'Dùng GIF',
  'feed.copyLink': 'Sao chép liên kết',
  'feed.linkCopied': 'Đã sao chép liên kết bài viết',
  'feed.savePost': 'Lưu bài viết',
  'feed.removeBookmark': 'Bỏ lưu',
  'feed.reportPost': 'Báo cáo bài viết',
  'feed.reportNoted': 'Báo cáo đã được ghi nhận. Đội kiểm duyệt đã nhận.',
  'feed.likeFailed': 'Không thể thích bài viết. Kiểm tra kết nối.',
  'feed.bookmarkFailed': 'Không thể lưu bài viết. Vui lòng thử lại.',
  // Chat
  'chat.title': 'Chat',
  'chat.messages': 'Tin nhắn',
  'chat.searchConversations': 'Tìm cuộc trò chuyện...',
  'chat.onlineNow': 'ĐANG TRỰC TUYẾN',
  'chat.new': 'Mới',
  'chat.chooseContact': 'Chọn liên hệ',
  'chat.deleteConversation': 'Xóa cuộc trò chuyện?',
  'chat.deleteConversationBody':
      'Thao tác này sẽ xóa cuộc trò chuyện với {name} khỏi hộp thư.',
  'chat.cancel': 'Hủy',
  'chat.delete': 'Xóa',
  'chat.deletedChat': 'Đã xóa cuộc trò chuyện với {name}',
  'chat.muted': 'Đã tắt tiếng {name}',
  'chat.unmuted': 'Đã bật tiếng {name}',
  'chat.unableLoadChats': 'Không thể tải tin nhắn',
  'chat.now': 'Vừa xong',
  'chat.yesterday': 'Hôm qua',
  'chat.conversationNotFound': 'Không tìm thấy cuộc trò chuyện',
  'chat.noConversations': 'Chưa có cuộc trò chuyện nào',
  'chat.typeMessage': 'Nhập tin nhắn...',
  'chat.online': 'Trực tuyến',
  'chat.offline': 'Ngoại tuyến',
  'chat.unableReaction': 'Không thể cập nhật phản ứng lúc này',
  'chat.sendCodeSnippet': 'Gửi đoạn mã',
  'chat.language': 'Ngôn ngữ',
  'chat.pasteCode': 'Dán mã của bạn vào đây...',
  'chat.sendCode': 'Gửi mã',
  'chat.sessionMissing': 'Phiên đã hết hạn. Vui lòng đăng nhập lại.',
  'chat.today': 'HÔM NAY',
  'chat.read': 'Đã đọc',
  'chat.delivered': 'Đã gửi',
  // Profile
  'profile.noBio': 'Người dùng chưa thêm giới thiệu.',
  // Leaderboard
  'leaderboard.title': 'Bảng xếp hạng',
  'leaderboard.heroTitle': 'Những nhà phát triển xuất sắc nhất tuần',
  'leaderboard.heroSubtitle':
      'Xếp hạng dựa trên uy tín, tương tác và sự đóng góp liên tục trong cộng đồng.',
  'leaderboard.unableLoad':
      'Không thể tải bảng xếp hạng.\nKéo xuống để thử lại.',
  'leaderboard.noData': 'Chưa có dữ liệu xếp hạng',
  'leaderboard.noDataSubtitle': 'Bảng xếp hạng sẽ hiển thị khi có hoạt động.',
  'leaderboard.howScores': 'Cách tính điểm',
  'leaderboard.colWeight': 'Hệ số',
  'leaderboard.colMetric': 'Chỉ số',
  'leaderboard.colDesc': 'Mô tả',
  // Playground
  'playground.title': 'Sân chơi lập trình',
  'playground.run': 'Chạy',
  'playground.running': 'Đang chạy...',
  'playground.consoleOutput': 'Kết quả',
  'playground.aiReview': 'AI Review',
  'playground.aiReviewDesc':
      'Phát hiện logic rủi ro và gợi ý cấu trúc tốt hơn.',
  'playground.aiExplain': 'AI Giải thích',
  'playground.aiExplainDesc': 'Phân tích đoạn mã bằng ngôn ngữ dễ hiểu.',
  'playground.runError': 'Lỗi: không thể chạy mã lúc này.',
  // Analytics
  'analytics.title': 'Thống kê hệ thống',
  'analytics.subtitle': 'Số liệu thời gian thực từ backend DevConnect',
  'analytics.recommendation': 'Gợi ý',
  'analytics.cache': 'Bộ nhớ đệm',
  'analytics.queues': 'Hàng đợi',
  'analytics.engagement': 'Tương tác',
  'analytics.unableLoad': 'Không thể tải thống kê',
  'analytics.tryAgain': 'Thử lại',
  'analytics.topInterestTags': 'Tags quan tâm hàng đầu',
  'analytics.recEngine': 'Công cụ gợi ý',
  'analytics.redisPerf': 'Hiệu suất Redis',
  'analytics.bullmqProc': 'Xử lý BullMQ',
  'analytics.cacheBreakdown': 'Phân tích cache',
  'analytics.topPosts': 'Bài viết nổi bật',
  'analytics.howItWorks': 'Cách hoạt động',
  'analytics.recExplain':
      '• Chức năng: Gợi ý bài viết bạn có thể thích dựa trên hoạt động trước đó.\n• Cách hoạt động: Hệ thống theo dõi những gì bạn thích, lưu và bình luận để xây dựng "hồ sơ sở thích".\n• Thuật toán: Dùng SVD (kỹ thuật toán học) để tìm xu hướng ẩn — ví dụ: nếu bạn thích bài về Flutter và một người khác cũng vậy, bạn sẽ thấy bài họ thích.\n• Khi mới dùng: Nếu bạn chưa có đủ 5 tương tác, hệ thống sẽ hiển thị bài viết phổ biến cho đến khi hiểu sở thích của bạn.\n• Cập nhật: Gợi ý được làm mới mỗi khi bạn tương tác với nội dung.',
  'analytics.cacheExplain':
      '• Chức năng: Tăng tốc ứng dụng bằng cách lưu dữ liệu hay dùng vào bộ nhớ nhanh (Redis).\n• Tại sao cần: Nếu không có cache, mỗi yêu cầu đều phải truy vấn cơ sở dữ liệu — rất chậm. Cache phục vụ dữ liệu tức thì.\n• Cách hoạt động: Khi bạn mở feed, ứng dụng kiểm tra cache trước. Nếu dữ liệu còn mới, sẽ hiển thị ngay ("hit"). Nếu không, sẽ lấy từ cơ sở dữ liệu ("miss").\n• Thời hạn: Cache feed hết hạn sau 60 giây, bảng xếp hạng 5 phút, kết quả AI 1 giờ.\n• Tỷ lệ Hit: Phần trăm yêu cầu được phục vụ từ cache. Càng cao = ứng dụng càng nhanh.',
  'analytics.queueExplain':
      '• Chức năng: Xử lý các tác vụ nặng (như AI) ở nền để ứng dụng không bị đơ.\n• Cách hoạt động: Khi bạn yêu cầu AI review code, công việc được xếp vào hàng đợi. Một worker nền sẽ nhận và xử lý, rồi trả kết quả.\n• Tại sao cần hàng đợi: Các tác vụ AI mất 5-15 giây. Không có hàng đợi, ứng dụng sẽ đứng yên trong lúc chờ.\n• Ý nghĩa các số:\n  - Hoàn thành: Công việc xử lý thành công\n  - Thất bại: Công việc gặp lỗi (tự động thử lại tối đa 3 lần)\n  - Đang chờ: Công việc đang xếp hàng chờ xử lý',
  'analytics.engageExplain':
      '• Chức năng: Đo lường hiệu suất nội dung của bạn trên nền tảng.\n• Các chỉ số:\n  - Lượt xem: Số người khác nhau đã xem bài viết (đếm theo địa chỉ IP)\n  - Lượt thích: Số người bấm nút tim\n  - Bình luận: Số phản hồi trên bài viết\n  - Người theo dõi: Số người đăng ký nhận cập nhật từ bạn\n• Công thức điểm xu hướng: thích×3 + bình luận×5 + lưu×2 + log(lượt xem)\n• Bài viết hàng đầu: Nội dung tốt nhất của bạn xếp theo công thức trên.',
  'search.title': 'Tìm kiếm',
  'search.recentSearches': 'Tìm kiếm gần đây',
  'search.clear': 'Xóa',
  'search.noResults': 'Không tìm thấy kết quả',
  'search.all': 'TẤT CẢ',
  'search.posts': 'BÀI VIẾT',
  'search.people': 'NGƯỜI DÙNG',
  'search.projects': 'DỰ ÁN',
  'search.results': 'kết quả',
  'search.goBack': 'Quay lại',
  'search.view': 'Xem',
  'search.developer': 'Lập trình viên',
  'search.hint': 'Tìm bài viết, người dùng, dự án...',
  'search.noRecent': 'Chưa có tìm kiếm gần đây',
  'search.trending': 'Chủ đề thịnh hành',
};
