const Map<String, String> stringsEn = {
  'app.name': 'DevConnect',
  'common.preview': 'Preview',
  'common.connected': 'Connected',
  'common.notLinked': 'Not linked',
  'common.public': 'Public',
  'common.private': 'Private',
  'common.everyone': 'Everyone',
  'common.followers': 'Followers',
  'common.nobody': 'Nobody',
  'common.off': 'Off',
  'common.light': 'Light',
  'common.dark': 'Dark',
  'common.english': 'English',
  'common.vietnamese': 'Tiếng Việt',
  'common.version': 'Version',
  'common.logout': 'Log Out',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.error': 'An error occurred',
  'common.retry': 'Retry',
  'common.all': 'All',
  'common.mentions': 'Mentions',
  'common.follows': 'Follows',
  'common.today': 'Today',
  'common.earlier': 'Earlier',
  'common.markAllRead': 'Mark all as read',
  'common.accept': 'Accept',
  'common.decline': 'Decline',
  'common.post': 'Post',
  'common.findFeature': 'Find a feature',
  'common.search': 'Search',
  'common.privateProfile': 'Private profile',
  'common.publicProfile': 'Public profile',
  'common.follow': 'Follow',
  'common.following': 'Following',
  'common.message': 'Message',
  'common.syncGithub': 'Sync GitHub',
  'common.synced': 'Synced',
  'common.noRecentContributions': 'No recent contributions',
  'common.featuredProject': 'Featured Project',
  'common.skills': 'Skills',
  'common.repos': 'Repos',
  'common.reputation': 'Reputation',
  'common.memberSince': 'Member since',
  'common.mentor': 'Mentor',
  'common.availableForGuidance': 'Available for guidance',
  'feed.forYou': 'For You',
  'feed.following': 'Following',
  'feed.trending': 'Trending',
  'group.primary': 'Primary',
  'group.social': 'Social',
  'group.opportunities': 'Opportunities',
  'group.tools': 'Tools',
  'group.system': 'System',
  'nav.home': 'Home',
  'nav.explore': 'Explore',
  'nav.chat': 'Chat',
  'nav.more': 'More',
  'nav.notifications': 'Notifications',
  'nav.profile': 'Profile',
  'nav.projects': 'Projects',
  'nav.jobs': 'Jobs',
  'nav.playground': 'Playground',
  'nav.analytics': 'Analytics',
  'nav.leaderboard': 'Leaderboard',
  'nav.live-code': 'Live Code Preview',
  'nav.settings': 'Settings',
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage your account, privacy, and preferences',
  'settings.account': 'ACCOUNT',
  'settings.privacy': 'PRIVACY',
  'settings.notifications': 'NOTIFICATIONS',
  'settings.appearance': 'APPEARANCE',
  'settings.about': 'ABOUT',
  'settings.editProfile': 'Edit Profile',
  'settings.changePassword': 'Change Password',
  'settings.githubIntegration': 'GitHub Integration',
  'settings.deleteAccount': 'Delete Account',
  'settings.profileVisibility': 'Profile Visibility',
  'settings.onlineStatus': 'Online Status',
  'settings.whoCanMessage': 'Who Can Message',
  'settings.pushNotifications': 'Push Notifications',
  'settings.emailNotifications': 'Email Notifications',
  'settings.quietHours': 'Quiet Hours',
  'settings.theme': 'Theme',
  'settings.language': 'Language',
  'settings.version': 'Version',
  'settings.logout': 'Log Out',
  'settings.public': 'Public',
  'settings.private': 'Private',
  'settings.languageEnglish': 'English',
  'settings.languageVietnamese': 'Tiếng Việt',
  'settings.displayNameRequired': 'Display name is required',
  'settings.editProfileSubtitle':
      'Update the basics people see on your profile.',
  'settings.profileUpdated': 'Profile updated',
  'settings.newPasswordTooShort': 'New password must be at least 8 characters',
  'settings.passwordsDoNotMatch': 'Passwords do not match',
  'settings.passwordChanged': 'Password changed',
  'settings.deleteAccountTitle': 'Delete account?',
  'settings.deleteAccountBody':
      'This removes your account from the current device and backend demo data.',
  'settings.delete': 'Delete',
  'settings.profileVisibilityTitle': 'Profile Visibility',
  'settings.whoCanMessageTitle': 'Who Can Message',
  'settings.quietHoursTitle': 'Quiet Hours',
  'settings.newPassword': 'New password',
  'settings.currentPassword': 'Current password',
  'settings.confirmNewPassword': 'Confirm new password',
  'settings.updatePassword': 'Update password',
  'settings.saveProfile': 'Save profile',
  'settings.displayName': 'Display name',
  'settings.shortBio': 'Short bio',
  'settings.skillsComma': 'Skills (comma separated)',
  'settings.publicProfile': 'Public profile',
  'settings.privateProfile': 'Private profile',
  'settings.connected': 'Connected',
  'settings.notLinked': 'Not linked',
  'settings.githubWebOnly':
      'GitHub OAuth is only available through the web redirect.',
  'settings.savedLocallySyncLater': 'Saved locally. Sync will retry later.',
  'notifications.title': 'Notifications',
  'notifications.subtitle': 'Stay updated with your activity and mentions',
  'notifications.unableLoad': 'Unable to load notifications right now.',
  'notifications.today': 'Today',
  'notifications.earlier': 'Earlier',
  'notifications.markAllRead': 'Mark all as read',
  'notifications.all': 'All',
  'notifications.mentions': 'Mentions',
  'notifications.follows': 'Follows',
  'notifications.empty': 'No notifications yet.',
  'notifications.teamInvite':
      "You've been invited to join the Team Flutter organization.",
  'notifications.accepted': 'You joined Team Flutter.',
  'notifications.declined': 'Team Flutter invite declined.',
  'profile.userNotFound': 'User not found',
  'profile.posts': 'Posts',
  'profile.projects': 'Projects',
  'profile.about': 'About',
  'profile.followers': 'Followers',
  'profile.following': 'Following',
  'profile.online': 'Online',
  'profile.offline': 'Offline',
  'profile.privateLockedTitle': 'This profile is private',
  'profile.privateLockedBody':
      'Only approved viewers can see posts, projects, and details.',
  'profile.noProjectsTitle': 'No projects yet',
  'profile.noProjectsBody':
      'Projects will appear here after this user creates or joins one.',
  'profile.gitHubConnected': 'GitHub Connected',
  'profile.gitHubNotLinked': 'GitHub not linked',
  'profile.gitHubConnectHint':
      'Connect GitHub with real OAuth before syncing data.',
  'profile.gitHubSynced': 'GitHub data synced',
  'profile.unableSyncGithub': 'Unable to sync GitHub right now',
  'profile.noRecentContributions': 'No recent contributions',
  'profile.featuredProject': 'Featured Project',
  'profile.skills': 'Skills',
  'profile.repos': 'Repos',
  'profile.reputation': 'Reputation',
  'profile.memberSince': 'Member since',
  'profile.mentor': 'Mentor',
  'profile.availableForGuidance': 'Available for guidance',
  'profile.quitProject': 'Quit Project',
  'profile.quitProjectConfirm': 'Are you sure you want to leave this project?',
  'profile.deleteProjectConfirm':
      'Are you sure you want to delete this project? This cannot be undone.',
  'profile.editSkills': 'Edit Skills',
  'profile.addSkillsHint': 'Tap edit to add your skills',
  'profile.noSkills': 'No skills listed',
  'feed.deletePostConfirm': 'Are you sure you want to delete this post?',
  'feed.postDeleted': 'Post deleted',
  'more.title': 'More',
  'more.findFeature': 'Find a feature',
  'more.preview': 'Preview',
  'feed.empty': 'No posts yet.',
  'auth.resetPassword': 'Reset password',
  'auth.resetDescription':
      'Enter the email you use for DevConnect. We will start the recovery flow for that account.',
  'auth.emailAddress': 'Email Address',
  'auth.sendRecovery': 'Send recovery instructions',
  'auth.enterValidEmail': 'Enter a valid email address',
  'auth.recoverySent':
      'If your account exists, recovery instructions are on the way.',
  'auth.join': 'Join DevConnect',
  'auth.startJourney': 'Start your developer journey',
  'auth.fullName': 'Full Name',
  'auth.username': 'Username',
  'auth.email': 'Email Address',
  'auth.password': 'Password',
  'auth.continue': 'Continue',
  'auth.alreadyHaveAccount': 'Already have an account? ',
  'auth.signIn': 'Sign In',
  'auth.secureAccount': 'Secure your account',
  'auth.choosePassword': 'Choose a password to protect your profile',
  'auth.weakPassword': 'Weak password',
  'auth.averagePassword': 'Average password',
  'auth.goodPassword': 'Good password',
  'auth.strongPassword': 'Strong password',
  'auth.createAccount': 'Create Account',
  'auth.accountCreated': 'Account Created',
  'auth.finishSetup': 'Finish setup',
  'auth.passwordMinLength': 'Password must be at least 8 characters',
  'auth.completeAllFields': 'Please complete all fields',
  'auth.reset': 'Reset',
  'errors.connectionTimeout':
      'Connection timed out. Please check your network.',
  'errors.sendTimeout': 'Request timed out. Please try again.',
  'errors.receiveTimeout': 'Response timed out. Please try again.',
  'errors.connectionError': 'Unable to connect. Please check your network.',
  'errors.badCertificate': 'Invalid security certificate.',
  'errors.cancelled': 'Request was cancelled.',
  'errors.unknown': 'An unknown error occurred.',
  'errors.invalidRequest': 'Invalid request.',
  'errors.sessionExpired': 'Session expired. Please sign in again.',
  'errors.permissionDenied': 'You do not have permission for this action.',
  'errors.notFound': 'Data not found.',
  'errors.conflict': 'Data conflict. Please try again.',
  'errors.invalidData': 'Invalid data.',
  'errors.tooManyRequests': 'Too many requests. Please wait and try again.',
  'errors.serverError': 'Server error. Please try again later.',
  'errors.serviceUnavailable': 'Service temporarily unavailable.',
  'errors.generic': 'Something went wrong. Please try again.',
  'errors.expectedObjectButGotList': 'Expected object but got list.',

  // Validators
  'validators.required': 'This field is required.',
  'validators.emailFormat': 'Email must be in format name@domain.com',
  'validators.emailTooLong': 'Email must be ≤254 characters',
  'validators.passwordTooShort': 'Password needs ≥8 characters',
  'validators.passwordNeedsLetter': 'Password needs at least 1 letter',
  'validators.passwordNeedsNumber': 'Password needs at least 1 digit',
  'validators.passwordNeedsSpecial':
      'Password needs at least 1 special character',
  'validators.passwordsDoNotMatch': 'Passwords do not match',
  'validators.usernameFormat': 'Username: 3-30 chars, only a-z, 0-9, _',
  'validators.usernameStartsWithUnderscore': 'Username cannot start with _',
  'validators.urlInvalid': 'Invalid URL',
  'validators.urlMissingScheme': 'URL must start with http:// or https://',
  'ai.unableReview': 'Unable to review code',
  'ai.unableExplain': 'Unable to explain code',
  'ai.tryUpdateSnippet': 'Try again after updating the snippet.',
  'ai.noMajorIssues': 'No major issues detected',
  'ai.snippetLooksClean':
      'The snippet looks clean enough to publish or demo as-is.',
  'ai.line': 'Line',
  'ai.concepts': 'Concepts',
  'ai.alternatives': 'Alternatives',
  'ai.complexity': 'Complexity',
  'ai.reviewInterrupted': 'Review interrupted',
  'ai.connectionLostReview':
      'The connection was lost. Try requesting the review again.',
  'ai.reviewing': 'AI is reviewing...',
  'ai.reviewComplete': 'Review complete',
  'ai.explanationInterrupted': 'Explanation interrupted',
  'ai.connectionLostExplanation':
      'The connection was lost. Try requesting the explanation again.',
  'ai.explaining': 'AI is explaining...',
  'ai.explanationComplete': 'Explanation complete',
  'ai.thinking': 'AI is thinking...',
  'ai.waitingResponse': 'Waiting for response...',
  'ai.typing': 'Typing...',
  // Projects
  'projects.title': 'Projects',
  'projects.marketplace': 'Project Marketplace',
  'projects.marketplaceSubtitle':
      'Discover open-source projects and find collaborators',
  'projects.all': 'All',
  'projects.lookingForDevs': 'Looking for Devs',
  'projects.openSource': 'Open Source',
  'projects.titleDescRequired': 'Title and description are required',
  'projects.created': 'Project created',
  'projects.join': 'Join',
  'projects.joined': 'Joined',
  'projects.alreadyJoined': 'You have already joined this project',
  'projects.unableJoin': 'Unable to join project right now',
  'projects.members': 'members',
  'projects.createProject': 'Create Project',
  'projects.createSubtitle':
      'Set up a new collaboration workspace for the community.',
  'projects.projectTitle': 'Project title',
  'projects.projectDescription': 'Describe what you are building',
  'projects.techStack': 'Tech stack (comma separated)',
  'projects.maxMembers': 'Max members',
  'projects.create': 'Create project',
  'projects.unableLoad': 'Unable to load projects.\nPull to try again.',
  'projects.noProjects': 'No projects available',
  'projects.noProjectsSubtitle': 'Check back later or create a new one.',
  // Jobs
  'jobs.title': 'Jobs',
  'jobs.hiringPulse': 'Hiring pulse',
  'jobs.openRoles': 'Open roles',
  'jobs.remote': 'Remote',
  'jobs.avgMatch': 'Avg match',
  'jobs.topMatch': 'Top match',
  'jobs.recent': 'Recent',
  'jobs.senior': 'Senior',
  'jobs.applyNow': 'Apply now',
  'jobs.applied': 'Applied',
  'jobs.signInToApply': 'Sign in to apply for jobs',
  'jobs.applicationFailed': 'Application failed. Try again.',
  'jobs.unableLoad': 'Unable to load jobs.\nPull to try again.',
  'jobs.noJobs': 'No jobs available',
  'jobs.noJobsSubtitle': 'Check back later for new openings.',
  'jobs.match': 'match',
  'jobs.allLevels': 'All Levels',
  'jobs.junior': 'Junior',
  'jobs.mid': 'Mid',
  'jobs.allSalaries': 'All Salaries',
  'jobs.filterTech': 'Tech Stack',
  'jobs.postJob': 'Post Job',
  'jobs.postJobSubtitle': 'Create a new job listing for your company',
  'jobs.jobTitle': 'Job title',
  'jobs.company': 'Company name',
  'jobs.location': 'Location (e.g. Ho Chi Minh)',
  'jobs.salary': r'Salary range (e.g. $2k-$4k)',
  'jobs.experience': 'Experience (e.g. Junior, Mid, Senior)',
  'jobs.techStackHint': 'Tech stack (comma separated)',
  'jobs.posted': 'Job posted!',
  'jobs.titleCompanyRequired': 'Title and company are required',
  'jobs.matchExplain':
      "Match % is computed by comparing your skills against the job's required tech stack. More skills overlap = higher match.",
  'jobs.search': 'Search jobs...',
  // Explore
  'explore.title': 'Explore',
  'explore.popularTopics': 'Popular Topics',
  'explore.trendingPosts': 'Trending Posts',
  'explore.topDevelopers': 'Top Developers',
  'explore.seeAll': 'See all',
  'explore.searchPlaceholder': 'Search posts, devs, projects...',
  'explore.aiPicks': 'AI Picks for You',
  // Feed
  'feed.defaultTitle': 'What are you working on?',
  'feed.addContent': 'Add some content before posting',
  'feed.aiReview': 'AI review before posting',
  'feed.keepEditing': 'Keep editing',
  'feed.postNow': 'Post now',
  'feed.post': 'Post',
  'feed.useGif': 'Use GIF',
  'feed.copyLink': 'Copy link',
  'feed.linkCopied': 'Post link copied',
  'feed.savePost': 'Save post',
  'feed.removeBookmark': 'Remove bookmark',
  'feed.reportPost': 'Report post',
  'feed.reportNoted': 'Report noted. Our moderation queue has it.',
  'feed.likeFailed': 'Could not like post. Check your connection.',
  'feed.bookmarkFailed': 'Failed to save post. Please try again.',
  // Chat
  'chat.title': 'Chat',
  'chat.messages': 'Messages',
  'chat.searchConversations': 'Search conversations...',
  'chat.onlineNow': 'ONLINE NOW',
  'chat.new': 'New',
  'chat.chooseContact': 'Choose a contact',
  'chat.deleteConversation': 'Delete conversation?',
  'chat.deleteConversationBody':
      'This removes your thread with {name} from the inbox.',
  'chat.cancel': 'Cancel',
  'chat.delete': 'Delete',
  'chat.deletedChat': 'Deleted chat with {name}',
  'chat.muted': 'Muted {name}',
  'chat.unmuted': 'Unmuted {name}',
  'chat.unableLoadChats': 'Unable to load chats',
  'chat.now': 'Now',
  'chat.yesterday': 'Yesterday',
  'chat.conversationNotFound': 'Conversation not found',
  'chat.noConversations': 'No conversations yet',
  'chat.typeMessage': 'Type a message...',
  'chat.online': 'Online',
  'chat.offline': 'Offline',
  'chat.unableReaction': 'Unable to update reaction right now',
  'chat.sendCodeSnippet': 'Send Code Snippet',
  'chat.language': 'Language',
  'chat.pasteCode': 'Paste your code here...',
  'chat.sendCode': 'Send Code',
  'chat.sessionMissing': 'User session missing. Please sign in again.',
  'chat.today': 'TODAY',
  'chat.read': 'Read',
  'chat.delivered': 'Delivered',
  // Profile
  'profile.noBio': 'This user has not added a bio yet.',
  // Leaderboard
  'leaderboard.title': 'Leaderboard',
  'leaderboard.heroTitle': "This week's most valuable builders",
  'leaderboard.heroSubtitle':
      'Rankings combine reputation, engagement, and consistency across the community.',
  'leaderboard.unableLoad': 'Unable to load leaderboard.\nPull to try again.',
  'leaderboard.noData': 'No ranking data',
  'leaderboard.noDataSubtitle':
      'Leaderboard will appear once activity is recorded.',
  'leaderboard.howScores': 'How Scores Are Calculated',
  'leaderboard.colWeight': 'Wt',
  'leaderboard.colMetric': 'Metric',
  'leaderboard.colDesc': 'Description',
  // Playground
  'playground.title': 'Code Playground',
  'playground.run': 'Run',
  'playground.running': 'Running...',
  'playground.consoleOutput': 'Console Output',
  'playground.aiReview': 'AI Review',
  'playground.aiReviewDesc':
      'Highlight risky logic and suggest cleaner structure.',
  'playground.aiExplain': 'AI Explain',
  'playground.aiExplainDesc': 'Break down the snippet in plain language.',
  'playground.runError': 'Error: unable to run code right now.',
  // Analytics
  'analytics.title': 'System Analytics',
  'analytics.subtitle': 'Real-time metrics from your DevConnect backend',
  'analytics.recommendation': 'Recommendation',
  'analytics.cache': 'Cache',
  'analytics.queues': 'Queues',
  'analytics.engagement': 'Engagement',
  'analytics.unableLoad': 'Unable to load analytics',
  'analytics.tryAgain': 'Try again',
  'analytics.topInterestTags': 'Top Interest Tags',
  'analytics.recEngine': 'Recommendation Engine',
  'analytics.redisPerf': 'Redis Performance',
  'analytics.bullmqProc': 'BullMQ Processing',
  'analytics.cacheBreakdown': 'Cache Breakdown',
  'analytics.topPosts': 'Top Posts',
  'analytics.howItWorks': 'How it works',
  'analytics.recExplain':
      '• What it does: Suggests posts you might like based on your past activity.\n• How: The system tracks what you like, bookmark, and comment on to build a "taste profile".\n• Algorithm: It uses SVD (a math technique) to find hidden patterns — e.g., if you like Flutter posts and so does another user, you\'ll see posts they liked too.\n• Fallback: If you\'re new (fewer than 5 interactions), you\'ll see popular posts instead until the system learns your preferences.\n• Updates: Your recommendations refresh every time you interact with content.',
  'analytics.cacheExplain':
      '• What it does: Speeds up the app by storing frequently-accessed data in fast memory (Redis).\n• Why: Without cache, every request would query the database — which is slow. Cache serves data instantly.\n• How it works: When you open your feed, the app checks cache first. If data exists and is fresh, it\'s served immediately (a "hit"). Otherwise, it fetches from the database (a "miss").\n• Expiration: Feed cache lasts 60 seconds, leaderboard 5 minutes, AI results 1 hour.\n• Hit Rate: Shows what percentage of requests are served from cache. Higher = faster app.',
  'analytics.queueExplain':
      '• What it does: Handles heavy tasks (like AI processing) in the background so the app stays fast.\n• How: When you request an AI code review, the job enters a queue. A background worker picks it up, processes it, and sends back the result.\n• Why queues: AI tasks take 5-15 seconds. Without queues, your app would freeze while waiting.\n• Counters explained:\n  - Completed: Jobs finished successfully\n  - Failed: Jobs that encountered errors (auto-retried up to 3 times)\n  - Waiting: Jobs currently in line to be processed',
  'analytics.engageExplain':
      '• What it does: Measures how well your content performs across the platform.\n• Metrics:\n  - Views: Unique visitors who saw your post (counted by IP address)\n  - Likes: People who clicked the heart button\n  - Comments: Replies on your posts\n  - Followers: People subscribed to your updates\n• Trending score formula: likes×3 + comments×5 + bookmarks×2 + log(views)\n• Top Posts: Your best-performing content ranked by the trending score above.',
  'search.title': 'Search',
  'search.recentSearches': 'Recent searches',
  'search.clear': 'Clear',
  'search.noResults': 'No results found',
  'search.all': 'ALL',
  'search.posts': 'POSTS',
  'search.people': 'PEOPLE',
  'search.projects': 'PROJECTS',
  'search.results': 'results',
  'search.goBack': 'Go back',
  'search.view': 'View',
  'search.developer': 'Developer',
  'search.hint': 'Search posts, people, projects...',
  'search.noRecent': 'No recent searches yet',
  'search.trending': 'Trending Topics',
};
